# Generated by Django 5.1 on 2024-09-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The symbol of the stock.', max_length=255, unique=True, verbose_name='Symbol')),
                ('expected_return', models.DecimalField(decimal_places=2, help_text='The expected annual gaining percentage.', max_digits=6, verbose_name='Expected Return')),
                ('volatility', models.DecimalField(decimal_places=2, help_text='The supposed annual changing percentage for the expected return.', max_digits=6, verbose_name='Volatility')),
                ('initial_price', models.DecimalField(decimal_places=2, help_text='The initial price of this stock.', max_digits=6, verbose_name='Initial Price')),
            ],
            options={
                'verbose_name': 'Stock information',
                'verbose_name_plural': 'Stock information',
                'ordering': ('symbol',),
            },
        ),
    ]
