# Generated by Django 5.1 on 2024-09-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='The symbol of the option.', max_length=255, unique=True, verbose_name='Symbol')),
                ('stock_symbol', models.CharField(help_text='The symbol of the original stock.', max_length=255, verbose_name='Stock Symbol')),
                ('option_type', models.CharField(help_text='Call option or put option.', max_length=255, verbose_name='Option Type')),
                ('volatility', models.DecimalField(decimal_places=2, help_text='The supposed annual changing percentage for the expected return.', max_digits=6, verbose_name='Volatility')),
                ('strike_price', models.DecimalField(decimal_places=2, help_text='The strike price of this option.', max_digits=6, verbose_name='Strike Price')),
                ('days_to_maturity', models.IntegerField(help_text='The days before the settlement day.', max_length=255, verbose_name='Days to Maturity')),
            ],
            options={
                'verbose_name': 'Option information',
                'verbose_name_plural': 'Option information',
                'ordering': ('symbol',),
            },
        ),
    ]
