# Generated by Django 5.1 on 2024-09-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='days_to_maturity',
            field=models.IntegerField(help_text='The days before the settlement day.', verbose_name='Days to Maturity'),
        ),
    ]
