# Generated by Django 5.1 on 2024-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, help_text='The symbol of the stock.', max_length=255, verbose_name='Symbol')),
                ('size', models.DecimalField(decimal_places=2, default=0, help_text='The size of this stock.', max_digits=36, verbose_name='Size')),
                ('user_id', models.IntegerField(blank=True, help_text='The position owner.', null=True, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Position information',
                'verbose_name_plural': 'Position information',
                'ordering': ('user_id',),
            },
        ),
    ]
